application: daoqiwang4
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: friends.app
  
libraries:                                                                      
- name: jinja2                                                                  
  version: latest 